apiVersion: v1
kind: Service
metadata:
  name: {{ include "gapura.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gapura.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector: {{- include "gapura.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.ports.http }}
    targetPort: http
    protocol: TCP
    {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePorts).http }}
    nodePort: {{ (.Values.service.nodePorts).http }}
    {{- end }}
  - name: https
    port: {{ .Values.ports.https }}
    targetPort: https
    protocol: TCP
    {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePorts).https }}
    nodePort: {{ (.Values.service.nodePorts).https }}
    {{- end }}
