apiVersion: v2
name: gapura
description: The Rust API gateway. Kubernetes Gateway API-native, one binary, no database.
type: application
version: 0.2.0
appVersion: "0.2.0"
kubeVersion: ">=1.29.0-0"
home: https://github.com/davidgrldo/gapura
sources:
  - https://github.com/davidgrldo/gapura
keywords:
  - gateway-api
  - ingress
  - proxy
  - rust
  - pingora
maintainers:
  - name: David Geraldo
    url: https://github.com/davidgrldo
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "true"
